### ISSUE TITLE
Error when parsing a toml file without trailing newline

### ISSUE THREAD

**Issue by JohnBjrk** [lpil/tom#1]
When parsing a string without a trailing newline tom returns `Unexpected("EOF", "\n")`

Example:
```gleam
  let assert Ok(toml) = tom.parse("lucy = \"cool\"")
```
 This fails on the `let assert`, but if a trailing newline is added like this:

```gleam
  let assert Ok(toml) = tom.parse("lucy = \"cool\"\n")
 ```

the result is `Ok`

I could not find anything in the `toml` specification about requiring a trailing newline.

**Comment by lpil** [comment]
Thank you
